
kind: PersistentVolume
apiVersion: v1
metadata:
  name: chris-store-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/chris-store-db-pv
