apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /home/prakash/openSource/miniChris-prakash/miniChRIS/miniChrisK8s
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.network/local: "true"
    io.kompose.service: queue
  name: queue
spec:
  containers:
    - image: rabbitmq:3
      name: queue
      resources: {}
  restartPolicy: OnFailure
status: {}
