apiVersion: v1
data:
 CELERY_BROKER_URL: amqp://queue:5672
 CHRIS_STORE_URL: http://chrisstore.local:8010/api/v1/
 DATABASE_HOST: chris-db-service
 DATABASE_PORT: "5432"
 DATABASE_URL: postgres://$(POSTGRES_USER):(POSTGRES_PASSWORD)@chris-db-service:5432/$(POSTGRES_DB)
 DJANGO_ALLOWED_HOSTS: '*'
 DJANGO_CORS_ORIGIN_ALLOW_ALL: "true"
 DJANGO_CORS_ORIGIN_WHITELIST: babymri.org
 DJANGO_SECRET_KEY: secret
 DJANGO_SECURE_PROXY_SSL_HEADER: ""
 DJANGO_SETTINGS_MODULE: config.settings.production
 DJANGO_USE_X_FORWARDED_HOST: "false"
 POSTGRES_DB: chris
 SWIFT_AUTH_URL: http://swift:8080/auth/v1.0
 POSTGRES_PASSWORD: chris1234
 POSTGRES_USER: chris
 STATIC_ROOT: /home/localuser/mod_wsgi-0.0.0.0:8000/htdocs/static/
 SWIFT_CONTAINER_NAME: users
 SWIFT_KEY: testing
 SWIFT_USERNAME: chris:chris1234
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-secrets-env
  name: secrets-env
