apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /home/prakash/openSource/miniChris-prakash/miniChRIS/miniChrisK8s
    kompose.version: 1.26.0 (40646f47)
    org.chrisproject.role: pman
  creationTimestamp: null
  labels:
    io.kompose.service: pman
  name: pman
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pman
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /home/prakash/openSource/miniChris-prakash/miniChRIS/miniChrisK8s
        kompose.version: 1.26.0 (40646f47)
        org.chrisproject.role: pman
      creationTimestamp: null
      labels:
        io.kompose.network/remote: "true"
        io.kompose.service: pman
    spec:
      containers:
        - command:
            - /entrypoint.sh
          env:
            - name: CONTAINER_ENV
              value: swarm
            - name: SECRET_KEY
              value: secret
          image: fnndsc/pman:next-4.0.0.a1.git.c245243
          name: pman
          ports:
            - containerPort: 5010
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: pman-claim0
            - mountPath: /entrypoint.sh
              name: pman-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: pman-claim0
          persistentVolumeClaim:
            claimName: pman-claim0
        - name: pman-claim1
          persistentVolumeClaim:
            claimName: pman-claim1
            readOnly: true
status: {}
